#!/usr/bin/env node
// Regenerate brain/index.md from page frontmatter. Node stdlib only (Node >= 22).
//
// Usage: node brain/scripts/build-index.mjs
//
// index.md is GENERATED — resolve any merge conflict in it by re-running this
// script, never by hand-editing (see brain/README.md "Merge safety").

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const brainDir = dirname(dirname(fileURLToPath(import.meta.url)));

const SECTIONS = [
  ['package', 'Packages (as-built)'],
  ['concept', 'Concepts'],
  ['decision', 'Decisions'],
  ['log', 'Log (newest first)'],
];

/** Parse the simple frontmatter subset the brain uses (string + inline-array values). */
function parseFrontmatter(text, file) {
  const match = /^---\n([\s\S]*?)\n---/.exec(text);
  if (!match) throw new Error(`${file}: missing frontmatter`);
  const meta = {};
  for (const line of match[1].split('\n')) {
    const kv = /^(\w+):\s*(.*)$/.exec(line);
    if (!kv) continue;
    const [, key, value] = kv;
    // Tolerate quoted scalar values (e.g. title: "Decision: ...").
    const trimmed = value.trim();
    const raw = /^(["']).*\1$/.test(trimmed) ? trimmed.slice(1, -1) : trimmed;
    meta[key] =
      raw.startsWith('[') && raw.endsWith(']')
        ? raw
            .slice(1, -1)
            .split(',')
            .map((s) => s.trim())
            .filter(Boolean)
        : raw.trim();
  }
  for (const required of ['title', 'type', 'summary', 'updated']) {
    if (!meta[required]) throw new Error(`${file}: frontmatter missing "${required}"`);
  }
  return meta;
}

function collectPages() {
  const pages = [];
  const skip = new Set(['README.md', 'index.md']);
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) {
        if (entry.name !== 'scripts') walk(path);
      } else if (entry.name.endsWith('.md') && !skip.has(relative(brainDir, path))) {
        pages.push({
          path: relative(brainDir, path).split(sep).join('/'),
          meta: parseFrontmatter(readFileSync(path, 'utf8'), path),
        });
      }
    }
  };
  walk(brainDir);
  return pages;
}

function buildIndex(pages) {
  const lines = [
    '# Brain index',
    '',
    '> GENERATED by `brain/scripts/build-index.mjs` — do not edit by hand.',
    '> Read this file first, then open only the pages relevant to your task.',
    '> Schema and workflows: [README.md](./README.md).',
    '',
  ];
  for (const [type, heading] of SECTIONS) {
    const rows = pages.filter((p) => p.meta.type === type);
    if (rows.length === 0) continue;
    // Log newest-first (date-prefixed filenames); everything else alphabetical.
    rows.sort((a, b) =>
      type === 'log' ? b.path.localeCompare(a.path) : a.path.localeCompare(b.path),
    );
    lines.push(`## ${heading}`, '');
    for (const { path, meta } of rows) {
      const pkgs =
        Array.isArray(meta.packages) && meta.packages.length > 0
          ? ` _(${meta.packages.join(', ')})_`
          : '';
      lines.push(`- [${meta.title}](./${path})${pkgs} — ${meta.summary}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

writeFileSync(join(brainDir, 'index.md'), buildIndex(collectPages()));
console.log('brain/index.md regenerated.');
